spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderCreated-out-0:
          destination: order-topic
          contentType: application/json
  application:
    name: order-service

server:
  port: 8082
